# Pytest fixtures for testing RAG system
# Place this file at: tests/conftest.py

import pytest
import json
import tempfile
from pathlib import Path
from typing import Dict, Any, List
import logging

# Configure logging for tests
logging.basicConfig(level=logging.DEBUG)

# ============================================================================
# FIXTURE 1: Mock Video Transcription Data (Updated for new system)
# ============================================================================

@pytest.fixture
def mock_video_transcript() -> Dict[str, Any]:
    """
    Mock video transcript in new format (as generated by VideoTranscriber).
    
    Simulates output from YouTube transcription or local video processing.
    This replaces the old mock_video_data fixture.
    """
    return {
        "video_id": "VIDEO_DOCKER_TUTORIAL",
        "title": "Docker Tutorial for Beginners - Full Course",
        "source_url": "https://www.youtube.com/watch?v=X48VuDHnJc0",
        "duration_seconds": 480,  # 8 minutes
        "video_transcripts": [
            {"id": 1, "timestamp": 0.0, "word": "Today"},
            {"id": 2, "timestamp": 0.5, "word": "we're"},
            {"id": 3, "timestamp": 1.0, "word": "going"},
            {"id": 4, "timestamp": 1.5, "word": "to"},
            {"id": 5, "timestamp": 2.0, "word": "learn"},
            {"id": 6, "timestamp": 2.5, "word": "about"},
            {"id": 7, "timestamp": 3.0, "word": "Docker"},
            {"id": 8, "timestamp": 3.5, "word": "installation"},
            # ... more tokens
            {"id": 50, "timestamp": 45.0, "word": "First"},
            {"id": 51, "timestamp": 45.5, "word": "go"},
            {"id": 52, "timestamp": 46.0, "word": "to"},
            {"id": 53, "timestamp": 46.5, "word": "docker"},
            {"id": 54, "timestamp": 47.0, "word": "dot"},
            {"id": 55, "timestamp": 47.5, "word": "com"},
            {"id": 56, "timestamp": 48.0, "word": "and"},
            {"id": 57, "timestamp": 48.5, "word": "download"},
            {"id": 58, "timestamp": 49.0, "word": "the"},
            {"id": 59, "timestamp": 49.5, "word": "installer"},
            # More tokens...
            {"id": 100, "timestamp": 120.0, "word": "installation"},
            {"id": 101, "timestamp": 120.5, "word": "is"},
            {"id": 102, "timestamp": 121.0, "word": "complete"},
        ]
    }


@pytest.fixture
def mock_video_transcript_kubernetes() -> Dict[str, Any]:
    """Mock Kubernetes video transcript."""
    return {
        "video_id": "VIDEO_K8S_BASICS",
        "title": "Kubernetes in 100 Seconds",
        "source_url": "https://www.youtube.com/watch?v=uVxB4VHgSZs",
        "duration_seconds": 100,
        "video_transcripts": [
            {"id": 1, "timestamp": 0.0, "word": "Kubernetes"},
            {"id": 2, "timestamp": 1.0, "word": "is"},
            {"id": 3, "timestamp": 2.0, "word": "a"},
            {"id": 4, "timestamp": 3.0, "word": "container"},
            {"id": 5, "timestamp": 4.0, "word": "orchestration"},
            {"id": 6, "timestamp": 5.0, "word": "platform"},
            # ... more tokens
            {"id": 20, "timestamp": 30.0, "word": "It"},
            {"id": 21, "timestamp": 31.0, "word": "manages"},
            {"id": 22, "timestamp": 32.0, "word": "containerized"},
            {"id": 23, "timestamp": 33.0, "word": "applications"},
            {"id": 24, "timestamp": 34.0, "word": "across"},
            {"id": 25, "timestamp": 35.0, "word": "clusters"},
        ]
    }


# ============================================================================
# FIXTURE 2: Mock PDF Data (Updated for new system)
# ============================================================================

@pytest.fixture
def mock_pdf_pages() -> Dict[int, str]:
    """
    Mock PDF content extracted by PDFFinder.
    
    Maps page number to extracted text.
    This replaces the old mock_pdf_data fixture.
    """
    return {
        1: "Docker and Containerization Guide\n\nChapter 1: Introduction",
        2: "Docker is a containerization platform that allows developers to package applications.",
        3: "Containerization provides consistency across development, testing, and production environments.",
        4: "Key concepts include images, containers, registries, and orchestration.",
        5: "Docker images are lightweight, standalone executable packages.",
        # More pages
        10: "Installation on macOS: 1. Download Docker Desktop from docker.com",
        11: "2. Run the installer and follow the setup wizard",
        12: "3. Verify installation with: docker --version",
        13: "4. Run your first container: docker run hello-world",
        14: "Best Practices for Containerization",
        15: "1. Keep images small - use minimal base images",
        16: "2. Use .dockerignore to exclude unnecessary files",
        17: "3. Implement proper health checks",
        18: "4. Use environment variables for configuration",
        19: "5. Security - scan images for vulnerabilities",
        20: "Summary and Next Steps",
    }


@pytest.fixture
def mock_pdf_files_kubernetes() -> Dict[int, str]:
    """Mock Kubernetes guide PDF."""
    return {
        1: "Kubernetes Complete Guide",
        2: "Kubernetes is an open-source container orchestration platform.",
        3: "It automates deployment, scaling, and management of containerized applications.",
        4: "Key components: Pod, Service, Deployment, StatefulSet, DaemonSet",
        5: "Architecture: Master node and Worker nodes",
        6: "Getting Started: Installation and setup",
        7: "Minikube for local development",
        8: "Kubectl command-line tool",
        9: "Creating and managing pods",
        10: "Understanding deployments",
    }


# ============================================================================
# FIXTURE 3: Test Queries with Expected Behavior
# ============================================================================

@pytest.fixture
def test_queries() -> Dict[str, Dict[str, Any]]:
    """
    Collection of test queries with expected behavior.
    
    Each query specifies:
    - question: The user's question
    - expected_source: 'video' or 'pdf' (what should answer it)
    - expected_match_quality: 'high', 'medium', 'low'
    - should_have_answer: True/False
    """
    return {
        "docker_install": {
            "question": "How do I install Docker on my MacBook?",
            "expected_source": "video",  # Docker Tutorial has installation section
            "expected_match_quality": "high",
            "should_have_answer": True,
            "keywords": ["install", "Docker", "MacBook"]
        },
        "containerization_practices": {
            "question": "What are the best practices for containerization?",
            "expected_source": "pdf",  # PDF section covers this
            "expected_match_quality": "high",
            "should_have_answer": True,
            "keywords": ["best practices", "containerization"]
        },
        "kubernetes_basics": {
            "question": "What is Kubernetes and how does it work?",
            "expected_source": "video",  # K8s video explains this
            "expected_match_quality": "high",
            "should_have_answer": True,
            "keywords": ["Kubernetes", "container orchestration"]
        },
        "pod_creation": {
            "question": "How do I create and manage pods in Kubernetes?",
            "expected_source": "pdf",  # Kubernetes PDF covers this
            "expected_match_quality": "high",
            "should_have_answer": True,
            "keywords": ["pod", "Kubernetes"]
        },
        "cooking_lasagna": {
            "question": "How do I cook a delicious lasagna?",
            "expected_source": "none",  # Not in any video or PDF
            "expected_match_quality": "none",
            "should_have_answer": False,
            "keywords": ["lasagna", "cooking"]
        },
        "edge_case_ambiguous": {
            "question": "container",  # Single word, ambiguous
            "expected_source": "video",  # Could match multiple sources
            "expected_match_quality": "medium",
            "should_have_answer": True,
            "keywords": ["container"]
        }
    }


# ============================================================================
# FIXTURE 4: Mock Chunked Data (for retrieval testing)
# ============================================================================

@pytest.fixture
def mock_video_chunks() -> List[Dict[str, Any]]:
    """Mock pre-chunked video data ready for vector storage."""
    return [
        {
            "chunk_id": "VIDEO_DOCKER_TUTORIAL_chunk_0",
            "video_id": "VIDEO_DOCKER_TUTORIAL",
            "video_title": "Docker Tutorial for Beginners",
            "start_token_id": 50,
            "end_token_id": 60,
            "start_timestamp": 45.0,
            "end_timestamp": 49.5,
            "text": "First go to docker dot com and download the installer for your operating system.",
            "score": 0.82  # Will be added during retrieval
        },
        {
            "chunk_id": "VIDEO_DOCKER_TUTORIAL_chunk_1",
            "video_id": "VIDEO_DOCKER_TUTORIAL",
            "video_title": "Docker Tutorial for Beginners",
            "start_token_id": 60,
            "end_token_id": 70,
            "start_timestamp": 50.0,
            "end_timestamp": 54.5,
            "text": "Once downloaded, run the installer and follow the setup wizard instructions.",
            "score": 0.78
        }
    ]


@pytest.fixture
def mock_pdf_paragraphs() -> List[Dict[str, Any]]:
    """Mock pre-chunked PDF data ready for vector storage."""
    return [
        {
            "para_id": "doc_docker_best_practices_p15_para1",
            "pdf_filename": "docker_containerization_best_practices.pdf",
            "page_number": 15,
            "paragraph_index": 1,
            "text": "Best Practices for Containerization include: 1) Keep images small by using minimal base images like alpine. 2) Use .dockerignore to exclude unnecessary files from the build context.",
            "score": 0.75
        },
        {
            "para_id": "doc_docker_best_practices_p16_para1",
            "pdf_filename": "docker_containerization_best_practices.pdf",
            "page_number": 16,
            "paragraph_index": 1,
            "text": "Security considerations: Always scan your Docker images for vulnerabilities using tools like Trivy or Snyk. Never run containers as root user.",
            "score": 0.71
        }
    ]


# ============================================================================
# FIXTURE 5: Temporary Directory Setup
# ============================================================================

@pytest.fixture
def temp_data_dir() -> Path:
    """Create temporary directory structure for testing."""
    with tempfile.TemporaryDirectory() as tmpdir:
        base_path = Path(tmpdir)
        
        # Create subdirectories
        (base_path / "videos").mkdir()
        (base_path / "videos" / "videos_input").mkdir()
        (base_path / "pdfs").mkdir()
        (base_path / "pdfs" / "pdfs_downloaded").mkdir()
        (base_path / "indices").mkdir()
        (base_path / "metadata").mkdir()
        (base_path / "logs").mkdir()
        
        yield base_path


# ============================================================================
# FIXTURE 6: Mock Ollama Embedder
# ============================================================================

@pytest.fixture
def mock_ollama_embedder():
    """Mock embedder that returns dummy embeddings."""
    class MockEmbedder:
        def __init__(self, dim: int = 384):
            import numpy as np
            self.dim = dim
            self._cache = {}
            self._use_cache = False

        def enable_cache(self):
            self._use_cache = True

        def _text_to_vector(self, text: str):
            """
            Deterministic, normalized embedding generator based on text.
            Produces `dim` floats with stable output for same input.
            """
            import numpy as np
            # Build embedding by summing per-word deterministic vectors.
            # This makes texts that share words more similar.
            words = [w.strip().lower() for w in text.split() if w.strip()]
            if not words:
                # deterministic zero-like vector for empty text
                vec = np.zeros(self.dim, dtype=float)
                return vec.tolist()

            vec = np.zeros(self.dim, dtype=float)
            for w in words:
                h = abs(hash(w)) % (2 ** 32)
                rng = np.random.RandomState(h)
                vec += rng.randn(self.dim)

            # Normalize to unit length to satisfy tests expecting normalized embeddings
            norm = np.linalg.norm(vec)
            if norm == 0:
                return vec.tolist()
            return (vec / norm).tolist()

        def embed_text(self, text: str):
            if self._use_cache and text in self._cache:
                return self._cache[text]
            vec = self._text_to_vector(text)
            if self._use_cache:
                self._cache[text] = vec
            return vec

        def embed_batch(self, texts: List[str]):
            return [self.embed_text(t) for t in texts]

    return MockEmbedder(dim=384)


# ============================================================================
# FIXTURE 7: Mock Qdrant Vector Store
# ============================================================================

@pytest.fixture
def mock_qdrant_store():
    """Mock vector store that simulates search operations."""
    class MockVectorStore:
        def __init__(self):
            self.video_vectors = []
            self.pdf_vectors = []
        
        def add_video_chunk(self, chunk_id: str, embedding, metadata):
            """Mock add video chunk."""
            self.video_vectors.append({
                "id": chunk_id,
                "embedding": embedding,
                "metadata": metadata
            })
        
        def add_pdf_paragraph(self, para_id: str, embedding, metadata):
            """Mock add PDF paragraph."""
            self.pdf_vectors.append({
                "id": para_id,
                "embedding": embedding,
                "metadata": metadata
            })
        
        def search_video(self, query_embedding, top_k: int = 3, threshold: float = 0.7):
            """Mock video search - return dummy results."""
            return [
                {
                    "chunk_id": "chunk_0",
                    "video_id": "VIDEO_TEST",
                    "text": "Sample video chunk",
                    "score": 0.85
                }
            ]
        
        def search_pdf(self, query_embedding, top_k: int = 3, threshold: float = 0.6):
            """Mock PDF search - return dummy results."""
            return [
                {
                    "para_id": "para_0",
                    "pdf_filename": "test.pdf",
                    "text": "Sample PDF paragraph",
                    "score": 0.75
                }
            ]
        
        def get_collections(self):
            """Return collection info."""
            return {
                "video_chunks": len(self.video_vectors),
                "pdf_paragraphs": len(self.pdf_vectors)
            }
    
    return MockVectorStore()


# ============================================================================
# FIXTURE 8: Mock LLM Configuration
# ============================================================================

@pytest.fixture
def mock_ollama_config():
    """Mock Ollama configuration."""
    class MockConfig:
        base_url = "http://localhost:11434"
        llm_model = "mistral"
        embedding_model = "all-MiniLM-L6-v2"
        chunk_size = 500
        chunk_overlap = 100
        video_threshold = 0.7
        pdf_threshold = 0.6
    
    return MockConfig()


# ============================================================================
# FIXTURE 9: Complete Mock RAG Pipeline
# ============================================================================

@pytest.fixture
def mock_rag_pipeline(mock_ollama_embedder, mock_qdrant_store, mock_ollama_config):
    """
    Complete mock RAG pipeline for end-to-end testing.
    
    Simulates the entire system without external dependencies.
    """
    class MockRAGPipeline:
        def __init__(self):
            self.embedder = mock_ollama_embedder
            self.vector_store = mock_qdrant_store
            self.config = mock_ollama_config
        
        def process_query(self, query: str):
            """Mock query processing."""
            # Generate embedding
            embedding = self.embedder.embed_text(query)
            
            # Search both sources
            video_results = self.vector_store.search_video(embedding)
            pdf_results = self.vector_store.search_pdf(embedding)
            
            return {
                "query": query,
                "video_results": video_results,
                "pdf_results": pdf_results,
                "best_source": "video" if video_results else "pdf"
            }
        
        def index_data(self, videos: List[Dict], pdfs: List[Dict]):
            """Mock indexing."""
            for video in videos:
                embedding = self.embedder.embed_text(video.get("text", ""))
                self.vector_store.add_video_chunk(
                    video.get("chunk_id"),
                    embedding,
                    video
                )
            
            for pdf in pdfs:
                embedding = self.embedder.embed_text(pdf.get("text", ""))
                self.vector_store.add_pdf_paragraph(
                    pdf.get("para_id"),
                    embedding,
                    pdf
                )
    
    return MockRAGPipeline()


# ============================================================================
# FIXTURE 10: Logger for Testing
# ============================================================================

@pytest.fixture
def test_logger():
    """Get logger for tests."""
    return logging.getLogger("test")
